### ISSUE TITLE
Work plan

### ISSUE THREAD

**Issue by timowka0304** [timowka0304/Word-Flow#1]
- [x] [Development of technical specifications](https://github.com/timowka0304/Word-Flow/wiki/Technical-task)
- [x] [Application (program) development](https://github.com/timowka0304/Word-Flow/issues/4)
- [x] Testing the application (program)
